Hw 5b
Adelina609/android_hw pull request #4
Opened 2018-10-14 15:28 UTC by Adelina609

hw5

2018-10-14 18:16 UTC, Adelina609 commented
![screenshot_20181014-205229](https://user-images.githubusercontent.com/36458707/46920377-21c0fb80-cff6-11e8-8cc6-96c5495975ad.jpg)
![screenshot_20181014-205241](https://user-images.githubusercontent.com/36458707/46920378-21c0fb80-cff6-11e8-88ca-2723a1869f81.jpg)
![screenshot_20181014-205148](https://user-images.githubusercontent.com/36458707/46920379-21c0fb80-cff6-11e8-86ae-3299f2f724ab.jpg)
![screenshot_20181014-205156](https://user-images.githubusercontent.com/36458707/46920380-22599200-cff6-11e8-9c6c-e15b474ee409.jpg)
![screenshot_20181014-205208](https://user-images.githubusercontent.com/36458707/46920382-22599200-cff6-11e8-9432-1b8595dd92f6.jpg)
![screenshot_20181014-205218](https://user-images.githubusercontent.com/36458707/46920383-238abf00-cff6-11e8-9829-b17cd293f713.jpg)

2018-10-14 18:29 UTC, NailShaykhrazievItis requested changes

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/java/adapter/FilmsAdapter.java
> +        public FilmsViewHolder(View view){
Добавь строку в начале класса и после переменных. Не надо настолько плотный код писать

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/java/adapter/FilmsAdapter.java
> +            view.setOnClickListener(new View.OnClickListener() {
Лучше это в бинд перенести, у тебя там сразу фильм придет, и не нужно будет вызывать getLayoutPosition()

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw3_b/DescriptionActivity.java
> +}
I see you

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw3_b/FilmDiffUtilCallBack.java
> +
extra line

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw3_b/FilmDiffUtilCallBack.java
> +    public Object getChangePayload(int oldItemPosition, int newItemPosition) {
можешь убрать метод, ты его все равно не переопределяешь, он ничего не делает

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw3_b/Films.java
> +}
В конце класса одна пустая строка

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/cv.xml
> +        >
Меня на это триггерит, но здесь это не принципиально

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_cardview.xml
> +
extra line

2018-10-14 18:29 UTC, NailShaykhrazievItis commented on app/src/main/res/layout/item_cardview.xml
> +                android:id="@+id/film_rating"
ctrl+alt+L

2018-10-15 19:07 UTC, Adelina609 commented
![1](https://user-images.githubusercontent.com/36458707/46972051-4be1ee80-d0c6-11e8-819e-db9613c8a614.jpg)
![2](https://user-images.githubusercontent.com/36458707/46972052-4c7a8500-d0c6-11e8-84a1-e70089c8a841.jpg)
![3](https://user-images.githubusercontent.com/36458707/46972070-52706600-d0c6-11e8-8164-3c19dfa37043.jpg)
![4](https://user-images.githubusercontent.com/36458707/46972071-52706600-d0c6-11e8-964e-8a1b71f4d11a.jpg)
![5](https://user-images.githubusercontent.com/36458707/46972072-5308fc80-d0c6-11e8-9c8e-91077d2d076e.jpg)
И да, все-таки 26 сдк выкрутился))

2018-10-15 19:59 UTC, NailShaykhrazievItis requested changes

2018-10-15 19:59 UTC, NailShaykhrazievItis commented on app/src/main/AndroidManifest.xml
> +            android:name=".RecyclerFragment"
это уже не активити, фрагменты не указываются в манифесте

2018-10-15 19:59 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw3_b/RecyclerFragment.java
> +    public static FilmsAdapter getAdapter() {
а зачем сио чудо?

2018-10-15 19:59 UTC, NailShaykhrazievItis commented on app/src/main/java/com/example/hw3_b/RecyclerFragment.java
> +
Вновь ты пыталась
Стилем своим удивить
Но тут экстра лайн

2018-11-06 22:20 UTC, closed without merging